apiVersion: batch/v1
kind: Job
metadata:
  name: cs-db-restore-job
  namespace: <cs-db namespace>
spec:
  template:
    spec:
        containers:
        - command:
          - sh
          - -c
          - /cs-db/br_cs-db.sh restore <cs-db namespace>
          image: icr.io/cpopen/cpfs/cpfs-utils:4.3.0 #4.1.0 if using CS 4.1, 4.2.0 if using CS 4.2
          imagePullPolicy: Always
          name: cs-db-restore-job
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 512Mi
              memory: 512Mi
            requests:
              cpu: 200m
              ephemeral-storage: 128Mi
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsNonRoot: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /cs-db/cs-db-backup
            name: cs-db-backup-mount
          - name: scripts
            mountPath: "/cs-db"
        dnsPolicy: ClusterFirst
        restartPolicy: OnFailure
        schedulerName: default-scheduler
        securityContext:
          runAsNonRoot: true
        serviceAccount: cs-db-backup-sa
        serviceAccountName: cs-db-backup-sa
        terminationGracePeriodSeconds: 30
        volumes:
        - name: cs-db-backup-mount
          persistentVolumeClaim:
            claimName: cs-db-backup-pvc
        - name: scripts
          configMap:
            name: cs-db-br-configmap
            defaultMode: 0777