apiVersion: v1
kind: Secret
metadata:
  name: ibm-dba-ums-secret
type: Opaque
stringData:
  adminUser: ""
  adminPassword: ""
  sslKeystorePassword: ""
  jwtKeystorePassword: ""
  teamserverClientID: ""
  teamserverClientSecret: ""
  ltpaPassword: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: ibm-dba-ums-db-secret
type: Opaque
stringData:
  oauthDBUser: ""
  oauthDBPassword: ""
  tsDBUser: ""
  tsDBPassword: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: ibm-dba-ums-ltpa-creation-secret
type: Opaque
data: