apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-to-ibm-licensing-service-instance
  namespace: "licNamespace"
  labels:
    component: cpfs3
spec:
  podSelector:
    matchLabels:
      app: ibm-licensing-service-instance
  ingress:
    - {}
  policyTypes:
    - Ingress
