apiVersion: v1
kind: Service
metadata:
  name: csssearch-cluster
spec:
  ports:
    - name: cssdefault
      protocol: TCP
      port: 8191
      targetPort: 8191
    - name: ccsssl
      protocol: TCP
      port: 8199
      targetPort: 8199
  selector:
    app: csssearch-cluster
  type: ClusterIP
  sessionAffinity: ClientIP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ecm-css-np
  namespace: $KUBE_NAME_SPACE
spec:
   podSelector: {}
   policyTypes:
    - Ingress
    - Egress
   ingress:
   - {}
   egress:
   - ports:
     - port: 53
       protocol: UDP
     - port: 53
       protocol: TCP
   - to:
     - namespaceSelector: {}
---    
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: csssearch-cluster
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: csssearch-cluster
    spec:
      imagePullSecrets:
        - name: admin.registrykey
      annotations:
        scheduler.alpha.kubernetes.io/affinity: |
          {
             "podAntiAffinity": {
               "preferredDuringSchedulingIgnoredDuringExecution": [
                 {
                     "weight":100,
                     "podAffinityTerm":{
                       "labelSelector": {
                         "matchExpressions": [
                           {
                             "key": "app",
                             "operator": "In",
                             "values": ["csssearch-cluster"]
                           }
                         ]
                       },
                     "topologyKey": "kubernetes.io/hostname"
                     }
                 }
               ]
             }
          }

    spec:
      containers:
      - image: <Repository for Docker Container Image>/default/css:latest
        imagePullPolicy: Always
        name: csssearch-cluster
        securityContext:
          # If deployment on OpenShift and image supports arbitrary uid,
          # remove runAsUser and pods will run with arbitrarily assigned user ID.
          runAsUser: 50001
          allowPrivilegeEscalation: false
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 4096Mi
            cpu: 1
        ports:
        - containerPort: 8191
          name: cssdefault
        - containerPort: 8199
          name: cssssl
        readinessProbe:
          tcpSocket:
            port: 8199
          initialDelaySeconds: 60
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 8199
          initialDelaySeconds: 120
          periodSeconds: 5
        env:
          - name: LICENSE
            value: "accept"
          - name: PRODUCT
            value: "DBAMC"
          - name: JVM_INITIAL_HEAP_PERCENTAGE
            value: "38"
          - name: JVM_MAX_HEAP_PERCENTAGE
            value: "50"
          - name: TZ
            value: "Etc/UTC"
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        volumeMounts:
          - name: csscfgstore-pvc
            mountPath: "/opt/IBM/ContentSearchServices/CSS_Server/data"
            subPath: CSS_Server_data/sslkeystore
          - name: csslogstore-pvc
            mountPath: "/opt/IBM/ContentSearchServices/CSS_Server/log"
            subPath: CSS_Server_log
          - name: csstempstore-pvc
            mountPath: "/opt/IBM/ContentSearchServices/CSS_Server/temp"
            subPath: CSS_Server_temp
          - name: cssindexstore-pvc
            mountPath: "/opt/ibm/indexareas"
            subPath: CSS_Indexes
          - name: csscustomstore-pvc
            mountPath: "/opt/IBM/ContentSearchServices/CSS_Server/config"
            subPath: css/CSS_Server_Config

      volumes:
        - name: csscfgstore-pvc
          persistentVolumeClaim:
            claimName: "css-cfgstore"
        - name: csslogstore-pvc
          persistentVolumeClaim:
            claimName: "css-logstore"
        - name: csstempstore-pvc
          persistentVolumeClaim:
            claimName: "css-tempstore"
        - name: cssindexstore-pvc
          persistentVolumeClaim:
            claimName: "css-indexstore"
        - name: csscustomstore-pvc
          persistentVolumeClaim:
            claimName: "css-customstore"
