apiVersion: turbonomic.com/v1alpha1
kind: OperatorResourceMapping
metadata:
  name: managementingresses.operator.ibm.com
  labels:
    component: cpfs
spec:
  resourceMappings:
    - srcResourceSpec:
        kind: Deployment
        componentNames:
          - management-ingress
      resourceMappingTemplates:
        - srcPath: .spec.template.spec.containers[?(@.name=="management-ingress")].resources
          destPath: .spec.resources