apiVersion: turbonomic.com/v1alpha1
kind: OperatorResourceMapping
metadata:
  name: nginxingresses.operator.ibm.com
  labels:
    component: cpfs
spec:
  resourceMappings:
    - srcResourceSpec:
        kind: Deployment
        componentNames:
          - default-http-backend
      resourceMappingTemplates:
        - srcPath: .spec.template.spec.containers[?(@.name=="default-http-backend")].resources
          destPath: .spec.defaultBackend.resources
    - srcResourceSpec:
        kind: Deployment
        componentNames:
          - nginx-ingress-controller
      resourceMappingTemplates:
        - srcPath: .spec.template.spec.containers[?(@.name=="nginx-ingress")].resources
          destPath: .spec.ingress.resources
