apiVersion: turbonomic.com/v1alpha1
kind: OperatorResourceMapping
metadata:
  name: commonwebuis.operators.ibm.com
  labels:
    component: cpfs
spec:
  resourceMappings:
    - srcResourceSpec:
        kind: Deployment
        componentNames:
          - common-web-ui
      resourceMappingTemplates:
        - srcPath: .spec.template.spec.containers[?(@.name=="common-web-ui")].resources
          destPath: .spec.resources
