apiVersion: turbonomic.com/v1alpha1
kind: OperatorResourceMapping
metadata:
  name: paps.operator.ibm.com
  labels:
    component: cpfs
spec:
  resourceMappings:
    - srcResourceSpec:
        kind: Deployment
        componentNames:
          - auth-pap
      resourceMappingTemplates:
        - srcPath: .spec.template.spec.containers[?(@.name=="icp-audit-service")].resources
          destPath: .spec.auditService.resources
        - srcPath: .spec.template.spec.containers[?(@.name=="auth-pap")].resources
          destPath: .spec.papService.resources
