# Default values for ibm-model-gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# general values
global:
  arch: amd64
  operatorNamespace: ""
  instanceNamespace: ""
  tetheredNamespace: []
  blockStorageClass: ""
  fileStorageClass: ""
  imagePullPrefix: icr.io  # the top level of image registry only, which can be overridden by user's private registry input
  imagePullSecret: ibm-entitlement-key
  licenseType: Enterprise
  licenseAccept: true
modelGateway:
  crVersion: 13.0.6
  operatorImageName: "cpopen/ibm-cpd-model-gateway-operator" # including the sub folder in which the image is saved
  # development operator image name "cp/ibm-cpd-model-gateway-operator" including the sub folder in which the image is saved
  devOperatorImageName: ""
  devImagePullPrefix: ""
  imageRegistryNamespace: "cp/cpd"
  operatorImageDigest:
    amd64: sha256:aa24398342468543ca793bbb04918ea5385915bdea57882892f44537013e280a  # pragma: allowlist secret
    ppc64le: sha256:4319c3358f9c68dbccf8d31ff1bf2e99f1eba273dba136253e54367a3a89270d  # pragma: allowlist secret
    s390x: sha256:f38ee661f856b656780502f7dfdf64bd0c1c83250695cf83addbb9a3f19bc75c  # pragma: allowlist secret
  scaleConfig: ""
  lite_install: false
  deploy_postgres: true
  deploy_redis: true
  external_redis: false
  externalRedisSecret: ""
  externalRedisCertificateSecret: ""
  cp4ba_license: false
  providerK8sSecret: false
  tenants: []
  tls_ca_secrets:
    - ibm-nginx-internal-tls-ca
  oTelInstanaConfig:
    oTel:
      metrics:
        insecure: true
        grpcAddr: "localhost:4317"
        httpAddr: "localhost:4318"
      traces:
        insecure: true
        grpcAddr: "localhost:4317"
        httpAddr: "localhost:4318"
      logs:
        insecure: true
        grpcAddr: "localhost:4317"
        httpAddr: "localhost:4318"
# service values
