apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lsr-backup-rolebinding
  namespace: <lsr instance namespace>
  labels:
    foundationservices.cloudpak.ibm.com: lsr-data
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lsr-backup-role
  namespace: <lsr instance namespace>
subjects:
- kind: ServiceAccount
  name: lsr-backup-sa
  namespace: <lsr instance namespace>