apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zen4-backup-rolebinding
  namespace: <zenservice namespace>
  labels:
    foundationservices.cloudpak.ibm.com: zen-data
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: zen4-backup-role
  namespace: <zenservice namespace>
subjects:
- kind: ServiceAccount
  name: zen4-backup-sa
  namespace: <zenservice namespace>