apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    kubernetes.io/description: "This policy allows pods to run with
      any UID and GID, but preventing access to the host."
  name: baca-anyuid-psp
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
    #rule: RunAsAny
  requiredDropCapabilities:
  - MKNOD
  - SETFCAP
  - NET_RAW
  - NET_BIND_SERVICE
  - KILL
  allowedCapabilities:
  - SETPCAP
  - AUDIT_WRITE
  - CHOWN
  - FOWNER
  - FSETID
  - SETUID
  - SETGID
  - SYS_CHROOT
  - DAC_OVERRIDE
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
    #rule: RunAsAny
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - persistentVolumeClaim
  forbiddenSysctls:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
  name: baca-anyuid-clusterrole
rules:
- apiGroups:
  - extensions
  resourceNames:
  - baca-anyuid-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use
