################################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2021. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-baw-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: "IBM BAW on Containers Catalog"
  image: icr.io/cpopen/ibm-cs-bawautomation-catalog@sha256:110dd9d1b75bbeb0a595b55667fbef2e7e4813004a38a31969f51fedaa2ff4c2
  publisher: IBM
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 45m
