################################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2021. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-baw-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: "IBM BAW on Containers Catalog"
  image: icr.io/cpopen/ibm-cs-bawautomation-catalog@sha256:1cbcd4fe682e480f95427bbe953923cd92948b6e98bad012b0a8f61550b1a02b
  publisher: IBM
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 45m
