################################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2021. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-baw-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: "IBM BAW on Containers Catalog"
  image: icr.io/cpopen/ibm-cs-bawautomation-catalog@sha256:b08f3e161b9c9c7bb07600e8991a02b5fef2dceda9d159c140dc225447754d7e
  publisher: IBM
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 45m
