################################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2021. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-baw-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-baw-operator
  publisher: IBM
  sourceType: grpc
  image: cp.stg.icr.io/cp/cp4a/ibm-cs-bawautomation-catalog@sha256:21436c514540e19baaa2a2ac143d32e83d48ab4ab0152a08b1c71801603cc21d
  updateStrategy:
    registryPoll:
      interval: 45m

