################################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2021. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-baw-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-baw-operator
  publisher: IBM
  sourceType: grpc
  image: cp.stg.icr.io/cp/cp4a/ibm-cs-bawautomation-catalog@sha256:686cd2d0b99faa7a1c4d8e7ff305dc2387ed9f07db3e586ec1c7ef82949f7db4
  updateStrategy:
    registryPoll:
      interval: 45m

