apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ibm-pfs-operator-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      name: ibm-pfs-operator
  unhealthyPodEvictionPolicy: AlwaysAllow