apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cpfs-util-cluster-role
  namespace: <operator namespace>
  labels:
    foundationservices.cloudpak.ibm.com: cpfs-util-backup
rules:
  - verbs:
      - get
      - list
      - create
    apiGroups:
      - ''
    resources:
      - namespaces