apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cpfs-util-cluster-rolebinding
  namespace: <operator namespace>
  labels:
    foundationservices.cloudpak.ibm.com: cpfs-util-backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cpfs-util-cluster-role
  namespace: <operator namespace>
subjects:
- kind: ServiceAccount
  name: cpfs-util-sa
  namespace: <operator namespace>