apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: setup-tenant-job-pvc
  namespace: <operator namespace>
  labels:
    foundationservices.cloudpak.ibm.com: cpfs-util-backup
spec:
  storageClassName: <storage class>
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem