apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: setup-tenant-job-role
  namespace: <operator namespace>
  labels:
    foundationservices.cloudpak.ibm.com: cpfs-util-backup
rules:
  - verbs:
      - create
      - get
      - delete
      - watch
      - update
      - list
      - patch
      - deletecollection
    apiGroups:
      - ''
      - batch
      - extensions
      - apps
      - policy
      - packages.operators.coreos.com
      - operator.ibm.com
      - operators.coreos.com
      - catalogsources.operators.coreos.com
      - namespacescopes.operators.coreos.com
      - cert-manager.io
      - operatorgroups.operators.coreos.com
      - rbac.authorization.k8s.io
      - "*"
    resources:
      - pods
      - pods/log
      - deployments
      - deployments/scale
      - statefulsets
      - statefulsets/scale
      - pods/exec
      - pods/portforward
      - endpoints
      - pods/status
      - jobs
      - secrets
      - commonservices
      - packagemanifests
      - configmaps
      - subscriptions
      - catalogsources
      - certificates
      - issuers
      - namespacescopes
      - operatorgroups
      - clusterserviceversions
      - roles
      - rolebindings
      - "*"
  - verbs:
      - get
      - list
    apiGroups:
      - postgresql.k8s.enterprisedb.io
    resources:
      - clusters