###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2025. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################

---
# vars file for roles/storage-perf-test
logfolder: '.logs'

cluster_infrastructure: AWS
cluster_name: femippo-ffpdv
storage_type: portworx
rwx_storagesize: 10Gi
storageClass_ReadWriteMany: portworx-shared-gp3
rwo_storagesize: 10Gi
storageClass_ReadWriteOnce: portworx-shared-gp3

#sysbench ocs random read
sysbench_random_read: true
rread_threads: 1,4,8,16
rread_fileTotalSize: 128m
rread_fileNum: 128
rread_fileBlockSize: 4k,8k,16k

#sysbench ocs random write
sysbench_random_write: true
rwrite_threads: 1,4,8,16
rwrite_fileTotalSize: 4096m
rwrite_fileNum: 4
rwrite_fileBlockSize: 4k,8k,16k

#sysbench ocs sequential read
sysbench_sequential_read: true
sread_threads: 1,2
sread_fileTotalSize: 4096m
sread_fileNum: 4
sread_fileBlockSize: 512m,1g

#sysbench ocs sequential write
sysbench_sequential_write: true
swrite_threads: 1,2
swrite_fileTotalSize: 4096m
swrite_fileNum: 4
swrite_fileBlockSize: 512m,1g