apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-$KUBE_NAME_SPACE-configdb-admin-$COUNTER
  # namespace: {{.Values.global.nameSpace}}
  labels:
    app: mongoadmin-configdb-pv
    configpv: configdb-admin-$COUNTER
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: mongoadmin-configdb-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: {{.Values.mongoDBConfig.storageCapacity}}
  nfs:
    # may use variable counter for different shard
    path: /exports/smartpages/$KUBE_NAME_SPACE/configdb-admin-$COUNTER
    server: $NFS_IP
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{.Values.storageClassName}}
