apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb-admin-shard$SHARDX-$COUNTER
  # namespace: {{ .Values.global.nameSpace }}
  labels:
    shard: admin-shard$SHARDX
    app: pv-admin-shard$SHARDX
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "pv-admin-shard$SHARDX"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: {{ .Values.mongoDBShard.storageCapacity }}
  nfs:
    path: /exports/smartpages/$KUBE_NAME_SPACE/mongodb-admin-shard$SHARDX-$COUNTER
    server: $NFS_IP
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{.Values.storageClassName}}
