apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cs-db-backup-pvc
  namespace: <cs-db namespace>
  labels:
    foundationservices.cloudpak.ibm.com: cs-db-data
spec:
  storageClassName: <storage class>
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem