apiVersion: batch/v1
kind: Job
metadata:
  name: zen5-backup-job
  namespace: zen
spec:
  template:
    spec:
        containers:
        - command:
          - sh
          - -c
          - ls
          - ./zen5/backup_zen5.sh <zenservice namespace>
          image: icr.io/cpopen/cpfs/cpfs-utils:4.2.0 #4.1.0 if using CS 4.1, 4.2.0 if using CS 4.2
          imagePullPolicy: Always
          name: zen5-backup-job
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 512Mi
              memory: 512Mi
            requests:
              cpu: 200m
              ephemeral-storage: 128Mi
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsNonRoot: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /zen5/zen-backup
            name: zen5-backup-mount
          - name: scripts
            mountPath: "/zen5"
        dnsPolicy: ClusterFirst
        restartPolicy: OnFailure
        schedulerName: default-scheduler
        securityContext:
          runAsNonRoot: true
        serviceAccount: zen5-backup-sa
        serviceAccountName: zen5-backup-sa
        terminationGracePeriodSeconds: 30
        volumes:
        - name: zen5-backup-mount
          persistentVolumeClaim:
            claimName: zen5-backup-pvc
        - name: scripts
          configMap:
            name: zen5-br-configmap
            defaultMode: 0777