apiVersion: devops.turbonomic.io/v1alpha1
kind: OperatorResourceMapping
metadata:
  name: ccx-orm
  namespace: {{ placeholder_namespace }}
spec:
  mappings:
    patterns:
      - owned:
          apiVersion: apps/v1
          kind: Deployment
          selector: reasoning-service
          path: .spec.template.spec.containers[?(@.name=="ibm-reasoning-service-deploy")].resources
        ownerPath: .spec.reasoning_service_configuration.resources
      - owned:
          apiVersion: apps/v1
          kind: Deployment
          selector: core_mcp_server
          path: .spec.template.spec.containers[?(@.name=="ibm-core-mcp-server-deploy")].resources
        ownerPath: .spec.core_mcp_server_configuration.resources
    selectors:
      reasoning-service:
        matchLabels:
          app.kubernetes.io/name: ibm-reasoning-service-deploy
    selectors:
      core_mcp_server:
        matchLabels:
          app.kubernetes.io/name: ibm-core-mcp-server-deploy
  owner:
    apiVersion: icp4a.ibm.com/v1
    kind: CCXAIServices
    name: ai-services
