# image:
#   repository: mycluster.icp:8500/$KUBE_NAME_SPACE/mongocluster
#   tag: latest
#   pullPolicy: Always

storageClassName: local-storage-admin
# nfsIP: $NFS_IP
# nameSpace: $KUBE_NAME_SPACE
# # existingSecret: true
# # wiredTigerCache: "$MONGO_WIREDTIGER_LIMIT"
wiredTigerCache: "0.5"
secretVolume: baca-secrets$KUBE_NAME_SPACE
mongosService: mongos-admin-service


mongoAdmin:
  # nodeSelector:
  #   mongo-admin$KUBE_NAME_SPACE: baca
  name: mongo-admin

logs:
  # claimname: $LOGPVC
  path: /var/log/
  # logLevel: $LOG_LEVEL

mongoDBConfig:
  storageCapacity: 10Gi
  labelName: mongodb-admin-configdb
  configPort: 27019
  replicas: $CONFIG_REPLICA
  replicaSetName: ConfigDBRepSetAdmin
  resources:
    limits:
      memory: "1Gi"
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "500m"

mongosRouter:
  name: mongos-admin-router
  routerPort: 27017
  replicas: $ROUTER_REPLICA
  configReplset: "$CONFIG_REPLSET_VALUE"
  resources:
    limits:
      memory: "1Gi"
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "500m"

mongoDBShard:
  # heritage: admin-shard
  # pvheritage: admin-shardpv
  storageCapacity: 15Gi
  shardPort: 27018
  replicas: $SHARD_REPLICA
  resources:
    limits:
      memory: "1Gi"
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "500m"

