# Label the resources using the labels_odm.sh script before running this recipe.
# Change  db-name=ICNDB ,db-name=ODMDB according to the DB name.
apiVersion: spp-data-protection.isf.ibm.com/v1alpha1
kind: Recipe
metadata:
  name: cp4ba-odm-backup-restore-recipe
  namespace: ibm-spectrum-fusion-ns 
spec:
  appType: cp4ba-odm
  groups:
    - name: all-resource
      type: resource
      includedNamespaces:
        - $REPLACE_NAMESPACE
    - name: all-cluster-resource
      type: resource
      includedResourceTypes:
        - clusterroles
        - oauths
        - users
        - clusterrolebindings
      includeClusterResources: true 
    - name: restore-cp4ba-ceadmin-user
      type: resource   
      backupRef: all-cluster-resource
      includedResourceTypes:
        - users
      includeClusterResources: true    
      labelSelector: custom-label=ceadmin 
    - name: restore-catalogsource-group
      type: resource
      backupRef: all-resource
      includedResourceTypes:
        - catalogsources  
    - name: restore-cp4ba-oauth
      type: resource 
      backupRef: all-cluster-resource
      includedResourceTypes:
        - oauths
      labelSelector: custom-label=cluster
      includeClusterResources: true  
    - name: restore-cp4ba-fips-status   
      type: resource   
      backupRef: all-resource
      includedResourceTypes:
        - configmaps
      labelSelector: custom-label=cp4ba
    - name: restore-ibm-cp4ba-common-config 
      type: resource   
      backupRef: all-resource
      includedResourceTypes:
        - configmaps
      labelSelector: custom-label=cp4ba
    - name: restore-cp4ba-users
      type: resource   
      backupRef: all-cluster-resource
      includedResourceTypes:
        - users
      includeClusterResources: true 
    - name: restore-cp4ba-ibm-entitlement-key
      type: resource   
      backupRef: all-resource
      includedResourceTypes:
        - secrets
      labelSelector: custom-label=cp4ba-ibm-entitlement-key           
    - name: restore-cp4ba-operatorgroup
      type: resource
      backupRef: all-resource
      includedResourceTypes:
        - operatorgroups
    - name: restore-cp4ba-subscription  
      type: resource 
      backupRef: all-resource     
      includedResourceTypes:
        - subscriptions     
      labelSelector: operators.coreos.com/ibm-cp4a-operator.$REPLACE_NAMESPACE=     
    - name: restore-cp4ba-resources
      type: resource 
      backupRef: all-resource  
      includedResourceTypes:
        - roles
        - rolebindings 
        - serviceaccounts          
    - name: restore-cp4ba-cluster-role-and-rolebinding
      type: resource  
      backupRef: all-cluster-resource 
      includedResourceTypes:
        - clusterroles
        - clusterrolebindings
      labelSelector: olm.owner.namespace=$REPLACE_NAMESPACE
      includeClusterResources: true  
    - name: restore-ldap-bind-secret
      type: resource
      backupRef: all-resource
      includedResourceTypes:
        - secrets 
      labelSelector: name=ldap-bind-secret
    - name: restore-ibm-ban-secret 
      type: resource
      backupRef: all-resource
      includedResourceTypes:
        - secrets 
      labelSelector: db-name=${ICN_DB_NAME}
    - name: restore-ibm-odm-db-secret 
      type: resource
      backupRef: all-resource
      includedResourceTypes:
        - secrets 
      labelSelector: db-name=${ODM_DB_NAME}
    - name: restore-ibm-cp4ba-db-ssl-secret
      type: resource
      backupRef: all-resource
      includedResourceTypes:
        - secrets 
      labelSelector: custom-label=cp4ba-ssl-secret 
    - name: restore-ibm-cp4ba-ldap-ssl-secret
      type: resource
      backupRef: all-resource
      includedResourceTypes:
        - secrets 
      labelSelector: custom-label=cp4ba-ssl-secret 
    - name: restore-cp4ba-icp4aclusters-resource
      type: resource
      backupRef: all-resource
      includedResourceTypes:
        - icp4aclusters
      labelSelector: app.kubernetes.io/instance=ibm-dba,app.kubernetes.io/name=ibm-dba  
    - name: zen-backup-volumes
      type: volume
      labelSelector: foundationservices.cloudpak.ibm.com=zen5-data         
    - name: zen-backup-resources
      type: resource
      labelSelector: foundationservices.cloudpak.ibm.com=zen5-data  
      backupRef: all-resource
      includedResourceTypes:
        - configmaps
        - deployments     
  hooks:       
  - name: cp4a-foundation-operator-check
    type: check
    namespace: $REPLACE_NAMESPACE
    selectResource: deployment
    labelSelector: operators.coreos.com/icp4a-foundation-operator.$REPLACE_NAMESPACE=
    timeout: 3600
    onError: fail
    chks:
    - name: replicasReady
      timeout: 3600
      onError: fail
      condition: "{$.spec.replicas} == {$.status.readyReplicas}"
  - name: cp4a-dpe-operator-check
    type: check
    namespace: $REPLACE_NAMESPACE
    selectResource: deployment
    labelSelector: operators.coreos.com/ibm-dpe-operator.$REPLACE_NAMESPACE=
    timeout: 3600
    onError: fail
    chks:
    - name: replicasReady
      timeout: 3600
      onError: fail
      condition: "{$.spec.replicas} == {$.status.readyReplicas}"  
  - name: cp4a-ads-operator-check
    type: check
    namespace: $REPLACE_NAMESPACE
    selectResource: deployment
    labelSelector: operators.coreos.com/ibm-ads-operator.$REPLACE_NAMESPACE=
    timeout: 3600
    onError: fail
    chks:
    - name: replicasReady
      timeout: 3600
      onError: fail
      condition: "{$.spec.replicas} == {$.status.readyReplicas}"  
  - name: cp4a-content-operator-check
    type: check
    namespace: $REPLACE_NAMESPACE
    selectResource: deployment
    labelSelector: operators.coreos.com/ibm-content-operator.$REPLACE_NAMESPACE=
    timeout: 3600
    onError: fail
    chks:
    - name: replicasReady
      timeout: 3600
      onError: fail
      condition: "{$.spec.replicas} == {$.status.readyReplicas}"       
  - name: cp4a-common-service-operator-check
    type: check
    namespace: $REPLACE_NAMESPACE
    selectResource: deployment
    labelSelector: operators.coreos.com/ibm-common-service-operator.$REPLACE_NAMESPACE=
    timeout: 3600
    onError: fail
    chks:
    - name: replicasReady
      timeout: 3600
      onError: fail
      condition: "{$.spec.replicas} == {$.status.readyReplicas}"  
  - name: cp4a-pfs-operator-check
    type: check
    namespace: $REPLACE_NAMESPACE
    selectResource: deployment
    labelSelector: operators.coreos.com/ibm-pfs-operator.$REPLACE_NAMESPACE=
    timeout: 3600
    onError: fail
    chks:
    - name: replicasReady
      timeout: 3600
      onError: fail
      condition: "{$.spec.replicas} == {$.status.readyReplicas}"  
  - name: cp4a-operator-check
    type: check
    namespace: $REPLACE_NAMESPACE
    selectResource: deployment
    labelSelector: operators.coreos.com/ibm-cp4a-operator.$REPLACE_NAMESPACE=
    timeout: 3600
    onError: fail
    chks:
    - name: replicasReady
      timeout: 3600
      onError: fail
      condition: "{$.spec.replicas} == {$.status.readyReplicas}"       
  - name: cp4a-odm-operator-check
    type: check
    namespace: $REPLACE_NAMESPACE
    selectResource: deployment
    labelSelector: operators.coreos.com/ibm-odm-operator.$REPLACE_NAMESPACE=
    timeout: 3600
    onError: fail
    chks:
    - name: replicasReady
      timeout: 3600
      onError: fail
      condition: "{$.spec.replicas} == {$.status.readyReplicas}"    
  - name: insights-engine-operator-check
    type: check
    namespace: $REPLACE_NAMESPACE
    selectResource: deployment
    labelSelector: operators.coreos.com/ibm-insights-engine-operator.$REPLACE_NAMESPACE=
    timeout: 3600
    onError: fail
    chks:
    - name: replicasReady
      timeout: 3600
      onError: fail
      condition: "{$.spec.replicas} == {$.status.readyReplicas}"   
  - name: cp4a-wfps-operator-check
    type: check
    namespace: $REPLACE_NAMESPACE
    selectResource: deployment
    labelSelector: operators.coreos.com/ibm-cp4a-wfps-operator.$REPLACE_NAMESPACE=
    timeout: 3600
    onError: fail
    chks:
    - name: replicasReady
      timeout: 3600
      onError: fail
      condition: "{$.spec.replicas} == {$.status.readyReplicas}"      
  - name: ibm-zen-operator-check
    type: check
    namespace: $REPLACE_NAMESPACE
    selectResource: deployment
    labelSelector: operators.coreos.com/ibm-zen-operator.$REPLACE_NAMESPACE=
    timeout: 6000
    onError: fail
    chks:
    - name: replicasReady
      timeout: 6000
      onError: fail
      condition: "{$.spec.replicas} == {$.status.readyReplicas}"  
  - name: ibm-iam-operator-check
    type: check
    namespace: $REPLACE_NAMESPACE
    selectResource: deployment
    labelSelector: operators.coreos.com/ibm-iam-operator.$REPLACE_NAMESPACE=
    timeout: 3600
    onError: fail
    chks:
    - name: replicasReady
      timeout: 3600
      onError: fail
      condition: "{$.spec.replicas} == {$.status.readyReplicas}"   
  - name: zen-backup-pod-exec
    type: exec
    namespace: $REPLACE_NAMESPACE
    labelSelector: foundationservices.cloudpak.ibm.com=zen5-data
    timeout: 3600
    onError: fail
    ops:
    - name: backup
      command: >
        ["/bin/bash", "-c", "rm -rf /zen5/zen-backup/database && rm -rf /zen5/zen-backup/objstorage && rm -rf /zen5/zen-backup/secrets && rm -rf /zen5/zen-backup/workspace; /zen5/backup_zen5.sh $REPLACE_NAMESPACE; /usr/bin/sync -f /zen5/zen-backup/"]
      container: zen5-backup-job
      timeout: 3600
    - name: restore
      command: >
        ["/bin/bash", "-c", "/zen5/restore_zen5.sh $REPLACE_NAMESPACE iaf-zen-cpdservice"]
      container: zen5-backup-job
      timeout: 3600  
  - name: zen-audit-check
    type: check
    namespace: $REPLACE_NAMESPACE
    selectResource: deployment
    labelSelector: app.kubernetes.io/component=zen-audit
    timeout: 3600
    onError: fail
    chks:
    - name: replicasReady
      timeout: 3600
      onError: fail
      condition: "{$.spec.replicas} == {$.status.readyReplicas}"                                                             
  - name: zen-core-check
    type: check
    namespace: $REPLACE_NAMESPACE
    selectResource: deployment
    labelSelector: component=zen-core
    timeout: 3600
    onError: fail
    chks:
    - name: replicasReady
      timeout: 3600
      onError: fail
      condition: "{$.spec.replicas} == {$.status.readyReplicas}"    
  - name: zen-core-api-check
    type: check
    namespace: $REPLACE_NAMESPACE
    selectResource: deployment
    labelSelector: component=zen-core-api
    timeout: 3600
    onError: fail
    chks:
    - name: replicasReady
      timeout: 3600
      onError: fail
      condition: "{$.spec.replicas} == {$.status.readyReplicas}"      
  - name: zen-watcher-check
    type: check
    namespace: $REPLACE_NAMESPACE
    selectResource: deployment
    labelSelector: component=zen-watcher
    timeout: 3600
    onError: fail
    chks:
    - name: replicasReady
      timeout: 3600
      onError: fail
      condition: "{$.spec.replicas} == {$.status.readyReplicas}"          
  - name: ibm-nginx-check
    type: check
    namespace: $REPLACE_NAMESPACE
    selectResource: deployment
    labelSelector: component=ibm-nginx
    timeout: 3600
    onError: fail
    chks:
    - name: replicasReady
      timeout: 3600
      onError: fail
      condition: "{$.spec.replicas} == {$.status.readyReplicas}"       
  - name: ibm-nginx-tester-check
    type: check
    namespace: $REPLACE_NAMESPACE
    selectResource: deployment
    labelSelector: component=ibm-nginx-tester
    timeout: 3600
    onError: fail
    chks:
    - name: replicasReady
      timeout: 3600
      onError: fail
      condition: "{$.spec.replicas} == {$.status.readyReplicas}"   
  - name: cp4ba-instance-check
    type: check
    namespace: $REPLACE_NAMESPACE
    selectResource: icp4a.ibm.com/v1/icp4aclusters
    nameSelector: icp4adeploy
    timeout: 3600 
    onError: fail
    chks:
    - name: readyStatus
      timeout: 3600
      onError: fail
      condition: "{$.status.conditions[?(@.type==\"Ready\")].reason} == {\"Successful\"}"              
  workflows:
  - name: backup
    sequence:
    - group: all-resource
    - group: all-cluster-resource
    - hook: zen-backup-pod-exec/backup    
    - group: zen-backup-volumes
    - group: zen-backup-resources
  - name: restore
    sequence:
    - group: restore-cp4ba-ceadmin-user
    - group: restore-catalogsource-group
    - group: restore-cp4ba-oauth
    - group: restore-cp4ba-fips-status
    - group: restore-ibm-cp4ba-common-config
    - group: restore-cp4ba-users
    - group: restore-cp4ba-ibm-entitlement-key
    - group: restore-cp4ba-operatorgroup
    - group: restore-cp4ba-subscription 
    - group: restore-cp4ba-resources  
    - group: restore-cp4ba-cluster-role-and-rolebinding 
    - hook: cp4a-foundation-operator-check/replicasReady  
    - hook: cp4a-dpe-operator-check/replicasReady  
    - hook: cp4a-ads-operator-check/replicasReady  
    - hook: cp4a-content-operator-check/replicasReady   
    - hook: cp4a-common-service-operator-check/replicasReady  
    - hook: cp4a-pfs-operator-check/replicasReady  
    - hook: cp4a-operator-check/replicasReady  
    - hook: cp4a-odm-operator-check/replicasReady  
    - hook: insights-engine-operator-check/replicasReady  
    - hook: cp4a-wfps-operator-check/replicasReady  
    - group: zen-backup-volumes         
    - group: zen-backup-resources
    - group: restore-ldap-bind-secret
    - group: restore-ibm-ban-secret
    - group: restore-ibm-cp4ba-db-ssl-secret
    - group: restore-ibm-cp4ba-ldap-ssl-secret
    - group: restore-ibm-odm-db-secret
    - group: restore-cp4ba-icp4aclusters-resource 
    - hook: ibm-zen-operator-check/replicasReady 
    - hook: ibm-iam-operator-check/replicasReady 
    - hook: zen-audit-check/replicasReady 
    - hook: zen-core-check/replicasReady 
    - hook: zen-core-api-check/replicasReady 
    - hook: zen-watcher-check/replicasReady 
    - hook: ibm-nginx-check/replicasReady 
    - hook: ibm-nginx-tester-check/replicasReady 
    - hook: cp4ba-instance-check/readyStatus 
    - hook: zen-backup-pod-exec/restore