apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-restore-job
  namespace: <keycloak namespace>
spec:
  template:
    spec:
        containers:
        - command:
          - sh
          - -c
          - /keycloak/br_keycloak.sh restore <keycloak namespace>
          image: icr.io/cpopen/cpfs/cpfs-utils:4.3.0 #4.1.0 if using CS 4.1, 4.2.0 if using CS 4.2
          imagePullPolicy: Always
          name: keycloak-restore-job
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 512Mi
              memory: 512Mi
            requests:
              cpu: 200m
              ephemeral-storage: 128Mi
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsNonRoot: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /keycloak/keycloak-backup
            name: keycloak-backup-mount
          - name: scripts
            mountPath: "/keycloak"
        dnsPolicy: ClusterFirst
        restartPolicy: OnFailure
        schedulerName: default-scheduler
        securityContext:
          runAsNonRoot: true
        serviceAccount: keycloak-backup-sa
        serviceAccountName: keycloak-backup-sa
        terminationGracePeriodSeconds: 30
        volumes:
        - name: keycloak-backup-mount
          persistentVolumeClaim:
            claimName: keycloak-backup-pvc
        - name: scripts
          configMap:
            name: keycloak-br-configmap
            defaultMode: 0777