apiVersion: v1
kind: Service
metadata:
  name: ecm-es-svc
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9080
      targetPort: 9080
    - name: https
      protocol: TCP
      port: 9443
      targetPort: 9443
  selector:
    app: esserver-cluster1
  type: NodePort
  sessionAffinity: ClientIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ecm-es
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: esserver-cluster1
    spec:
      imagePullSecrets:
        - name: admin.registrykey
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - esserver-cluster1
              topologyKey: "kubernetes.io/hostname"
      containers:
      - image: <Repository for Docker Container Image>/default/extshare:latest
        imagePullPolicy: Always
        name: ecm-es
        securityContext:
          # If deployment on OpenShift and image supports arbitrary uid,
          # remove runAsUser and pods will run with arbitrarily assigned user ID.
          runAsUser: 50001
          allowPrivilegeEscalation: false
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 1536Mi
            cpu: 1
        ports:
        - containerPort: 9080
          name: http
        - containerPort: 9443
          name: https
        env:
          - name: LICENSE
            value: "accept"
          - name: JVM_INITIAL_HEAP_PERCENTAGE
            value: "40"
          - name: JVM_MAX_HEAP_PERCENTAGE
            value: "66"
          - name: TZ
            value: "Etc/UTC"
          - name: ICNDBTYPE
            value: "db2"
          - name: ICNJNDIDS
            value: "ECMClientDS"
          - name: ICNSCHEMA
            value: "ICNDB"
          - name: ICNTS
            value: "ICNDB"
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        readinessProbe:
          httpGet:
            path: /contentapi/rest/share/v1/info
            port: 9080
            httpHeaders:
              - name: Content-Encoding
                value: gzip
          initialDelaySeconds: 180
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /contentapi/rest/share/v1/info
            port: 9080
            httpHeaders:
              - name: Content-Encoding
                value: gzip
          initialDelaySeconds: 600
          periodSeconds: 5
        volumeMounts:
          - name: escfgstore-pvc
            mountPath: "/opt/ibm/wlp/usr/servers/defaultServer/configDropins/overrides"
            subPath: es/configDropins/overrides
          - name: eslogstore-pvc
            mountPath: "/opt/ibm/wlp/usr/servers/defaultServer/logs"
            subPath: es/logs

      volumes:
        - name: escfgstore-pvc
          persistentVolumeClaim:
            claimName: "es-icp-cfgstore"
        - name: eslogstore-pvc
          persistentVolumeClaim:
            claimName: "es-icp-logstore"
