apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-backup-pvc
  namespace: <keycloak namespace>
  labels:
    foundationservices.cloudpak.ibm.com: keycloak-data
spec:
  storageClassName: <storage class>
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem