################################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2019. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
# CP4BA 24.0.0-IF010 catalog
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cp4a-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-cp4a-operator
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-cp-automation-catalog@sha256:e0c0cac97b5629b7826d954b82195a9e57619fafbdadf4069e84bf179477ad42
  grpcPodConfig:
    securityContextConfig: restricted
---
# IBM CS Flink Operator Catalog 1.20.2 (2.0.19)
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-opencontent-flink
  namespace: openshift-marketplace
spec:
  displayName: IBM CS Opencontent Flink Catalog
  publisher: IBM
  sourceType: grpc
  image: >-
    icr.io/cpopen/ibm-opencontent-flink-operator-catalog@sha256:d3970f055e5bfbe77cd4fbfa9da86bb39597b9474c19fd0a3190cb568c7534af
  priority: 100
  grpcPodConfig:
    securityContextConfig: restricted
---
# IBM CS Opensearch Operator Catalog 1.1.2667
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cs-opensearch-catalog
  namespace: openshift-marketplace
spec:
  displayName: IBM CS Opencontent Opensearch Catalog
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/opencontent-elasticsearch-operator-catalog@sha256:a34169228887ff93161584753c990bb82a5520ad7945dfa1ff4078e70aede592
  priority: 100
  grpcPodConfig:
    securityContextConfig: restricted
---
# IBM Certificate Manager 4.2.23
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cert-manager-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-cert-manager-4.2.23
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-cert-manager-operator-catalog@sha256:c704e8c7418cd6df1e766bd8aea2975d0e7c988509c28456bf37ca5b62c18ac8
  grpcPodConfig:
    securityContextConfig: restricted
---
# IBM License Manager 4.2.24
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-licensing-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-licensing-4.2.24
  publisher: IBM
  image: icr.io/cpopen/ibm-licensing-catalog@sha256:8e2bee469a186599167283316e29f9e6e4f413b7bc7cdebcd3828ecf8f81b956
  sourceType: grpc
  grpcPodConfig:
    securityContextConfig: restricted
---
# IBM Cloud Foundational Services 4.6.22
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cs-install-catalog-v4-6-22
  namespace: openshift-marketplace
  annotations:
    bedrock_catalogsource_priority: '1'
spec:
  displayName: IBM CS Install Operators
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-cs-install-catalog@sha256:ae3fd1dd0f21b10f6c4c80f2089b4476dc1c858abeb9dd31073a428ddb32d38a
  priority: 100
  grpcPodConfig:
    securityContextConfig: restricted
---
# IBM Business Teams Service version 3.35.13 (1.0.39)
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-bts-operator-catalog-v3-35
  namespace: openshift-marketplace
  annotations:
    bedrock_catalogsource_priority: '1'
spec:
  displayName: BTS Operator
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-bts-operator-catalog@sha256:25458e158903b6645f17f3b2ec076f60a595872680cc6b8cdca596434239c4b7
  grpcPodConfig:
    securityContextConfig: restricted
---
# IBM CS IM Operator Catalog 4.5.19
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-iam-operator-catalog
  namespace: openshift-marketplace
  annotations:
    bedrock_catalogsource_priority: '1'
spec:
  displayName: IBM IAM Operator Catalog
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-iam-operator-catalog@sha256:f8c4ba1862a1185b9bdd08737af7537753070f62c2a861235caae93ab2f8830d
  priority: 100
  grpcPodConfig:
    securityContextConfig: restricted
---
# IBM Zen Operator Catalog 5.1.21 (CASE 3.1.22)
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-zen-operator-catalog
  namespace: openshift-marketplace
  annotations:
    bedrock_catalogsource_priority: '1'
spec:
  displayName: IBM Zen Operator Catalog
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-zen-operator-catalog@sha256:cdbfa293c4c6f6428bec1e9dc4e3180653b98004b0f69bbfd15ebf61b088720c
  priority: 100
  grpcPodConfig:
    securityContextConfig: restricted
---
# IBM Events Operator Catalog 5.2.1
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-events-operator-catalog-v5-2-1
  namespace: openshift-marketplace
  annotations:
    bedrock_catalogsource_priority: '1'
spec:
  displayName: IBM Events Operator Catalog-v5.2.1
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-events-operator-catalog@sha256:228ea92d69daa2350e151d1fe6b14e6fb56eadd0d3b5b5872178180747297687
  priority: 100
  grpcPodConfig:
    securityContextConfig: restricted
---
# Cloud Native PostgresSQL Version 1.28.2 (CASE 5.40.0+20260511.071333.2716)(Postgresql Image Version 14.22)
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cloud-native-postgresql-catalog
  namespace: openshift-marketplace
  annotations:
    bedrock_catalogsource_priority: '1'
spec:
  displayName: Cloud Native Postgresql Catalog
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-cpd-cloud-native-postgresql-operator-catalog@sha256:563e0032a3d96e39a7f94cc1bcd4fea5ec38d6249da591baaec1473cf58cf7a9
  priority: 100
  grpcPodConfig:
    securityContextConfig: restricted
---
# IBM FileNet Content Manager Standalone catalog 5.6.0-IF010.
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-fncm-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-fncm-operator
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-fncm-catalog@sha256:db890c4809a55d74306861bf6a62481c361d0fe6efc0fde0d013728bc6c82702
  grpcPodConfig:
    securityContextConfig: restricted
