################################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2019. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
# CP4BA 25.0.0-IF005 catalog
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cp4a-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-cp4a-operator
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-cp-automation-catalog@sha256:4cfcec90224315324151e8cb49a202bae9c2e3bf5ca70facfa6dca77545441b5
  grpcPodConfig:
    securityContextConfig: restricted
---
# IBM CS Flink Operator Catalog 1.20.2 (2.0.19)
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-opencontent-flink
  namespace: openshift-marketplace
spec:
  displayName: IBM CS Opencontent Flink Catalog
  publisher: IBM
  sourceType: grpc
  image: >-
    icr.io/cpopen/ibm-opencontent-flink-operator-catalog@sha256:9f673bd4ab11a5734cdf79bf18c7c5bcb52ded1c7faf9e24e3355f3f6e4edb97
  priority: 100
  grpcPodConfig:
    securityContextConfig: restricted
---
# IBM CS Opensearch Operator Catalog 1.4.1
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-opensearch-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: IBM CS Opencontent Opensearch Catalog
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/opencontent-ibm-opensearch-operator-catalog@sha256:17e6f19f43ae3f83ea8fddcd81d0b7cf42ec1e5b94ab353fdc3249679b24dcad
  priority: 100
  grpcPodConfig:
    securityContextConfig: restricted
---
# IBM Certificate Manager 4.2.21
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cert-manager-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-cert-manager-4.2.21
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-cert-manager-operator-catalog@sha256:f3280ce1a45a6f7139b79bba402d137f1ac661699baf21e566f03d17d7807b59
  grpcPodConfig:
    securityContextConfig: restricted
---
# IBM License Manager 4.2.21
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-licensing-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-licensing-4.2.21
  publisher: IBM
  image: icr.io/cpopen/ibm-licensing-catalog@sha256:fbef092ea62c545c311f48c0cc6d313f37f5a660253930e92ed00bacde684f96
  sourceType: grpc
  grpcPodConfig:
    securityContextConfig: restricted
---
# IBM Cloud Foundational Services 4.18.1
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cs-install-catalog-v4-18-0
  namespace: openshift-marketplace
  annotations:
    bedrock_catalogsource_priority: '1'
spec:
  displayName: IBM CS Install Operators
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-cs-install-catalog@sha256:f76c75ccb46689bdfd7ad30169593c96895aba5458962681aaa3cef74fb7a324
  priority: 100
  grpcPodConfig:
    securityContextConfig: restricted
---
# IBM Business Teams Service version 3.35.10
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-bts-operator-catalog-v3-35
  namespace: openshift-marketplace
  annotations:
    bedrock_catalogsource_priority: '1'
spec:
  displayName: BTS Operator-3.35.10
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-bts-operator-catalog@sha256:aa7a33be9d37ae09354e3ea29711849406d07b8b1435830c0af79bf82e2d72aa
  grpcPodConfig:
    securityContextConfig: restricted
---
# IBM CS IM Operator Catalog 4.17.1
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-iam-operator-catalog-4-17-0
  namespace: openshift-marketplace
  annotations:
    bedrock_catalogsource_priority: '1'
spec:
  displayName: IBM IAM Operator Catalog
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-iam-operator-catalog@sha256:845eb294d21e6af580f70424f7c57886194cd5644bb1d57e31d8be6818b4fc2c
  priority: 100
  grpcPodConfig:
    securityContextConfig: restricted
---
# IBM Zen Operator Catalog 6.4.5+20260501.202141.4
# we only update the catalog name when the channel is changed.
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-zen-operator-catalog-6-4-0
  namespace: openshift-marketplace
  annotations:
    bedrock_catalogsource_priority: '1'
spec:
  displayName: IBM Zen Operator Catalog
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-zen-operator-catalog@sha256:0c1fde3f2b76479bb76ce853a28a071ac4e9b51bceee1af39b581c51f8ca746c
  priority: 100
  grpcPodConfig:
    securityContextConfig: restricted
---
# IBM Events Operator Catalog 5.2.1
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-events-operator-catalog-v5-2-1
  namespace: openshift-marketplace
  annotations:
    bedrock_catalogsource_priority: '1'
spec:
  displayName: IBM Events Operator Catalog-v5.2.1
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-events-operator-catalog@sha256:228ea92d69daa2350e151d1fe6b14e6fb56eadd0d3b5b5872178180747297687
  priority: 100
  grpcPodConfig:
    securityContextConfig: restricted
---
# Cloud Native PostgresSQL Version 1.25.6 (CASE 5.31.1+20260310.150029.2714)(Postgresql Image Version 14.22)
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cloud-native-postgresql-catalog
  namespace: openshift-marketplace
  annotations:
    bedrock_catalogsource_priority: '1'
spec:
  displayName: Cloud Native Postgresql Catalog
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-cpd-cloud-native-postgresql-operator-catalog@sha256:79042063952ee9683c972a83ebfa9085f8899ea73403ff7a0de74e537d7b84b3
  priority: 100
  grpcPodConfig:
    securityContextConfig: restricted
---
# IBM FileNet Content Manager Standalone catalog for 5.7.0-IF004
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-fncm-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-fncm-operator
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-fncm-catalog@sha256:ffafeece30f790f61759599ad2f9c1b4d0bb8ef46c32134cfd53687b30780746
  grpcPodConfig:
    securityContextConfig: restricted
