apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-to-ibm-licensing-service-reporter
  namespace: "lsrNamespace"
  labels:
    component: cpfs3
spec:
  podSelector:
    matchLabels:
      app: ibm-license-service-reporter-instance
  ingress:
    - {}
  policyTypes:
    - Ingress
