apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-edb-postgres
  namespace: "zenNamespace"
  labels:
    component: cpfs3
spec:
  podSelector:
    matchExpressions:
    - key: k8s.enterprisedb.io/cluster
      operator: Exists
  policyTypes:
  - Egress
  egress:
  - {}
