apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-ibm-postgres
  namespace: "zenNamespace"
  labels:
    component: cpfs3
    service: ibm-pg
spec:
  podSelector:
    matchExpressions:
    - key: pg.ibm.com/cluster
      operator: Exists
  policyTypes:
  - Egress
  egress:
  - {}