apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-zen-minio-create-buckets-job
  namespace: "zenNamespace"
  labels:
    component: cpfs3
spec:
  podSelector:
    matchLabels:
      component: "zen-minio-create-buckets-job"
  policyTypes:
  - Egress
  egress:
  - {}