apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-zen-validate-metastore-edb-connection-job
  namespace: "zenNamespace"
  labels:
    component: cpfs3
spec:
  podSelector:
    matchLabels:
      component: "zen-validate-metastore-edb-connection-job"
  policyTypes:
  - Egress
  egress:
  - {}