apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ibm-ccx-ai-services-operator-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      name: ibm-ccx-ai-services-operator
  unhealthyPodEvictionPolicy: AlwaysAllow
