apiVersion: operator.ibm.com/v1
kind: IBMUsageMetering
metadata:
  name: ibmusagemetering
  namespace: REPLACE_NAMESPACE
spec:
  license:
    accept: true
  sender:
    softwareCentral:
      enable: true
      entitlementKeySecret: REPLACE_SECRET_NAME
