apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    kubernetes.io/description: "This policy is required to allow ibm-dba-ek pods running elasticsearch to use privileged containers"
  name: bai-psp
spec:
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
    - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bai-role
  namespace: bai
rules:
  - apiGroups:
      - extensions
    resourceNames:
      - bai-psp
    resources:
      - podsecuritypolicies
    verbs:
      - use
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bai-release-bai-psp-sa