apiVersion: batch/v1
kind: Job
metadata:
  name: zen4-restore-job
  namespace: <zenservice namespace>
spec:
  template:
    spec:
        containers:
        - command:
          - sh
          - -c
          - /zen4/zen4-br.sh <zenservice namespace> false
          image: icr.io/cpopen/cpfs/cpfs-utils:4.3.0 #4.1.0 if using CS 4.1, 4.2.0 if using CS 4.2
          imagePullPolicy: Always
          name: zen4-restore-job
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 512Mi
              memory: 512Mi
            requests:
              cpu: 200m
              ephemeral-storage: 128Mi
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsNonRoot: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /user-home
            name: user-home-mount
          - mountPath: /certs
            name: metastore-secret
          - mountPath: /tmp/backup
            name: zen-metastoredb-backup-scripts
          - name: scripts
            mountPath: "/zen4"
          - name: ext
            mountPath: /zen4/extensions
        dnsPolicy: ClusterFirst
        restartPolicy: OnFailure
        schedulerName: default-scheduler
        securityContext:
          runAsNonRoot: true
        serviceAccount: zen4-backup-sa
        serviceAccountName: zen4-backup-sa
        terminationGracePeriodSeconds: 30
        volumes:
        - name: user-home-mount
          persistentVolumeClaim:
            claimName: zen-backup-pvc
        - name: metastore-secret
          secret:
            defaultMode: 484
            secretName: metastore-secret
        - configMap:
            defaultMode: 511
            name: zen-metastoredb-backup-scripts
          name: zen-metastoredb-backup-scripts
        - name: scripts
          configMap:
            name: zen4-br-configmap
            defaultMode: 0777
        - emptyDir: {}
          name: ext