kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: egress-ibm-flink-operand
  namespace: "flinkNamespace"
spec:
  podSelector: 
    matchLabels:
      type: flink-standalone-kubernetes
  egress:
    - ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 9443
      to:
        - podSelector:
            matchLabels:
              apiserver: 'true'
          namespaceSelector: {}
    - ports:
      - protocol: TCP
        port: 443
      - protocol: TCP
        port: 8081
      - protocol: TCP
        port: 9081
      to:
        - podSelector: {}
  policyTypes:
    - Egress