apiVersion: v1
kind: Pod
metadata:
  name: folder-creation-baca
  labels:
    app: folder-creation-baca
  namespace: baca
spec:
  volumes:
    - name: sp-config-pvc-baca
      persistentVolumeClaim:
          claimName: sp-config-pvc-baca
    - name: sp-log-pvc-baca
      persistentVolumeClaim:
          claimName: sp-log-pvc-baca
    - name: sp-data-pvc-baca
      persistentVolumeClaim:
          claimName: sp-data-pvc-baca
  containers:
    - name: folder-creation-baca
      image: nginx:latest
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: sp-config-pvc-baca
          mountPath: /config
        - name: sp-log-pvc-baca
          mountPath: /logs
        - name: sp-data-pvc-baca
          mountPath: /data