###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2020. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: icp4a.ibm.com/v1
kind: ICP4ACluster
metadata:
  name: icp4aca
  labels:
    app.kubernetes.io/instance: ibm-dba
    app.kubernetes.io/managed-by: ibm-dba
    app.kubernetes.io/name: ibm-dba
    release: 20.0.2.1
spec:
  appVersion: 20.0.2.1
  
  #####################################################################################################################
  ##  The contents of this template CR file reflect only the specific parameters and configuration 
  ##  settings applicable to the represented ICP4A capability. 
  ##   
  ##  These values/configuration sections are to be used when manually assembling or updating the main 
  ##  ICP4A CR that is being applied in order to install an ICP4A environment. 
  ##  
  ##  If you are in the process of preparing a new install of an ICP4A environment, 
  ##  you should merge the required values and configuration sections from this file into the   
  ##  starting point CR template: ibm_cp4a_cr_enterprise_foundation.yaml available in the
  ##  same location as this template. 
  ##  
  ##  If you are updating an existing ICP4A environment, you should merge the required values and configuration
  ##  sections from this template into your existing CR file already applied in the environment.  
  ##  
  ######################################################################################################################
  shared_configuration:

    ## Use this parameter to specify the license for the CP4A deployment and
    ## the possible values are: non-production and production and if not set, the license will
    ## be defaulted to production.  This value could be different from the other licenses in the CR.
    sc_deployment_license: "<Required>"
    
    ## All CP4A components must use/share the image_pull_secrets to pull images    
    image_pull_secrets: 
    - admin.registrykey
    
    ## All CP4A components must use/share the same docker image repository.  For example, if IBM Entitlement Registry is used, then 
    ## it should be "cp.icr.io".  Otherwise, it will be a local docker registry.    
    sc_image_repository: cp.icr.io
    
    ## The deployment type as selected by the user.  Possible values are: demo, enterprise.    
    sc_deployment_type: enterprise
    
    ## The platform to be deployed specified by the user.  Possible values are: OCP, ROKS,IKS and other.  This is normally populated by the User script 
    ## based on input from the user.    
    sc_deployment_platform:

    ## CP4A patterns or capabilities to be deployed.  This CR represents the "contentanalyzer" pattern, which includes the following 
    ## mandatory components: ums, rr, icn (BAN/Navigator), bastudio    
    sc_deployment_patterns: contentanalyzer
    
    ## The optional components to be installed if listed here.  This is normally populated by the User script based on input from the user. 
    ## Content Analyzer does not have optional components to customize.
    sc_optional_components:
   
    ## All CP4A components must use/share the root_ca_secret in order for integration    
    root_ca_secret: icp4a-root-ca

    ## For OCP, this is used to create route, you should input a valid hostname in the required field.
    sc_deployment_hostname_suffix: "{{ meta.name }}.<Required>"    
    
    ## On OCP 3.x and 4.x, the User script will populate these three (3) parameters based on your input for "enterprise" deployment.
    ## If you manually deploying without using the User script, then you would provide the different storage classes for the slow, medium
    ## and fast storage parameters below.  If you only have 1 storage class defined, then you can use that 1 storage class for all 3 parameters.   
    storage_configuration:
      sc_slow_file_storage_classname: "<Required>"
      sc_medium_file_storage_classname: "<Required>"
      sc_fast_file_storage_classname: "<Required>"    

  ## The beginning section of database configuration for CP4A
  datasource_configuration:
    ## The database configuration for ACA (Content Analyzer)
    dc_ca_datasource:
      ## Provide the database type from your infrastructure.  The possible values are "db2" or "db2HADR" or "oracle".    
      dc_database_type: "<Required>"
      ## Provide the primary database server name and if your database server name cannot be resolvable by DNS, then provide the corresponding IP address for the `database_IP` parameter below.
      database_servername: "<Required>"
      ## Provide the name of the BASE database for ACA.  For example: "BASECA"
      database_name: "<Required>"
      ## Provide the names of the TENANT databases for ACA.
      tenant_databases:
      - "<Required>"
      ## Provide the database server port.  For Db2, the default is "50000".   For Oracle, the default is "1521".
      database_port: "<Required>"
      ## Enable SSL/TLS for database communication. Refer to Knowledge Center for more info.
      dc_database_ssl_enabled: false 
      
      ######################################################################################
      ## If the database type is "Db2HADR", then complete the rest of the parameters below.
      ## Otherwise, remove or comment out the rest of the parameters below.
      ######################################################################################
      
      ## Provide the standby database server name and if your standby database server name cannot be resolvable by DNS, then provide the corresponding IP address for the `dc_hadr_standby_ip` parameter below.      
      dc_hadr_standby_servername: "<Required>"
      ## Provide the standby database server port.  For Db2, the default is "50000".
      dc_hadr_standby_port: "<Required>"
      ## Provide the validation timeout.  If not preference, keep the default value.
      dc_hadr_validation_timeout: 15
      ## Provide the retry internal.  If not preference, keep the default value.
      dc_hadr_retry_interval_for_client_reroute: 15
      ## Provide the max # of retries.  If not preference, keep the default value.
      dc_hadr_max_retries_for_client_reroute: 3
      ## Provide the primary database server IP address if database_servername cannot be resolved by DNS.
      database_ip: "<Required>"
      ## Provide the standby database server IP address if dc_hadr_standby_servername cannot be resolved by DNS.      
      dc_hadr_standby_ip: "<Required>"

