###############################################################################
##
##Licensed Materials - Property of IBM
##
##(C) Copyright IBM Corp. 2020. All Rights Reserved.
##
##US Government Users Restricted Rights - Use, duplication or
##disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
##
###############################################################################
apiVersion: icp4a.ibm.com/v1
kind: ICP4ACluster
metadata:
  name: icp4adeploy
  labels:
    app.kubernetes.io/instance: ibm-dba
    app.kubernetes.io/managed-by: ibm-dba
    app.kubernetes.io/name: ibm-dba
    release: 20.0.2.1
spec:
  appVersion: 20.0.2.1


  #################################################################################################################
  ##  The contents of this template CR file reflect only the specific parameters and configuration
  ##  settings applicable to the represented ICP4A capability.
  ##
  ##  These values/configuration sections are to be used when manually assembling or updating the main
  ##  ICP4A CR that is being applied in order to install an ICP4A environment.
  ##
  ##  If you are in the process of preparing a new install of an ICP4A environment,
  ##  you should merge the required values and configuration sections from this file into the
  ##  starting point CR template: ibm_cp4a_cr_enterprise_foundation.yaml available in the
  ##  same location as this template.
  ##
  ##  If you updating an existing ICP4A environment, you should merge the required values and configuration
  ##  sections from this template in the main ICP4A CR file already applied in the environment.
  ##
  ######################################################################################################################
  shared_configuration:

    ## CP4A patterns or capabilities to be deployed. This is not used by ADW. ADW doesn't support enterprise pattern yet
    sc_deployment_patterns: "digitalworker"

    # ADW only reacts to one optional component : bai
    sc_optional_components:

  ########################################################################
  ########   IBM Business Automation Digital Worker               ########
  ########################################################################
  # You can further customize the adw_configuration section as explained in the knowledge center.
  # See ibm_cp4a_cr_enterprise_FC_digitalworker.yaml file in descriptors/patterns for all parameters and their default values.
  adw_configuration:

    global:
      # Optional : dedicated ADW image pull secret. default : none
      imagePullSecret: adw-reg-cred
      kubernetes:
        # Optional : the name of the Pod Security Policy you created to override the default one.
        serviceAccountName: adw-psp-sa
    # Optional : the name of the adw secret you created to override the default one.
    adwSecret: "adw-secret"

    userManagement:
      dwAdmin: # the Digital Worker user ID with admin rights. If not set, it will default to `oidcUserName` configured in adwSecret
      searchUsers:
        filterAttributes: # Coma separated attributes used to search users in LDAP through SCIM. Default: "displayName,uid"
        resultAttribute: # Attribute of user returned from SCIM. Default: "displayName"
      searchGroups:
        filterAttributes: # Coma separated attributes used to search groups in LDAP through SCIM. Default: "displayName"
        resultAttribute: # Attribute of group returned from SCIM. Default: "displayName"

    # Optional : trace, debug, info, warn, error. Default : info
    logLevel: "info"

    designer:
      image:
        repository: # can be used to pull the image from a specific docker registry
        tag: # can be used to pull a specific version of the image.
        pullPolicy: # "Always, IfNotPresent" default : not set
      hostname: "https://designer.{{ shared_configuration.sc_deployment_hostname_suffix }}"
      service_type: # Route or ClusterIP or LoadBalancer
      port: # The port used by external users, exposed as a `LoadBalancer` service
      resources:
        limits:
          cpu: # The maximum amount of CPU to allocate to each pod
          memory: # The maximum memory to allocate to each pod
        requests:
          memory: # The minimum memory required to start a pod
          cpu: # The minimum amount of CPU required to start a pod


    runtime:
      image:
        repository: # can be used to pull the image from a specific docker registry
        tag: # can be used to pull a specific version of the image.
        pullPolicy: # "Always, IfNotPresent" default : not set
      # the number of replicas for the runtime statefulset. Default is 1.
      replicas : 1
      hostname: "https://runtime.{{ shared_configuration.sc_deployment_hostname_suffix }}"
      service_type: # Route or ClusterIP or LoadBalancer
      port: # The port used by external users, exposed as a `LoadBalancer` service
      resources:
        limits:
          cpu: # The maximum amount of CPU to allocate to each pod
          memory: # The maximum memory to allocate to each pod
        requests:
          memory: # The minimum memory required to start a pod
          cpu: # The minimum amount of CPU required to start a pod
      persistence:
        storageClassName: "{{ shared_configuration.storage_configuration.sc_fast_file_storage_classname}}"
        useDynamicProvisioning: # default : true. Set to false if you want to manually defined storage
        existingClaimName: # An Existing PVC name for the runtime volume

    management:
      image:
        repository: # can be used to pull the image from a specific docker registry
        tag: # can be used to pull a specific version of the image.
        pullPolicy: # "Always, IfNotPresent" default : not set
      # the number of replicas for the management statefulset. Default is 1.
      replicas : 1
      hostname: "https://management.{{ shared_configuration.sc_deployment_hostname_suffix }}"
      service_type: # Route or ClusterIP or LoadBalancer
      port: # The port used by external users, exposed as a `LoadBalancer` service
      resources:
        limits:
          cpu: # The maximum amount of CPU to allocate to each pod
          memory: # The maximum memory to allocate to each pod
        requests:
          memory: # The minimum memory required to start a pod
          cpu: # The minimum amount of CPU required to start a pod
      persistence:
        storageClassName: "{{ shared_configuration.storage_configuration.sc_medium_file_storage_classname}}"
        useDynamicProvisioning: # default : true. Set to false if you want to manually defined storage
        existingClaimName: # An Existing PVC name for management volume
      runLogLevel: # The default pino logging level for runs. Available log levels: silent, fatal, error, warn, info, debug, trace. Default is info
      runTimeout: #The default timeout for runs in seconds

    init:
      image:
        repository: # can be used to pull the image from a specific docker registry
        tag: # can be used to pull a specific version of the image.
        pullPolicy: # "Always, IfNotPresent" default : not set

    mongo:
      image:
        repository: # can be used to pull the image from a specific docker registry
        tag: # can be used to pull a specific version of the image.
        pullPolicy: # "Always, IfNotPresent" default : not set
      # the number of replicas for the mongo replicaset. Default is 1.
      replicas : 1
      persistence:
        storageClassName: "{{ shared_configuration.storage_configuration.sc_fast_file_storage_classname}}"
        useDynamicProvisioning: # default : true. Set to false if you want to manually defined storage
        size: # The minimum size of the persistent volume

    npmRegistry:
      image:
        repository: # can be used to pull the image from a specific docker registry
        tag: # can be used to pull a specific version of the image.
        pullPolicy: # "Always, IfNotPresent" default : not set
      # the number of replicas for the npmRegistry statefulset. Default is 1.
      replicas : 1
      persistence:
        storageClassName: "{{ shared_configuration.storage_configuration.sc_medium_file_storage_classname}}"
        useDynamicProvisioning: # default : true. Set to false if you want to manually defined storage
        size: # The minimum size of the persistent volume
        existingClaimName: # An Existing PVC name for npmRegistry volume

    setup:
      image:
        repository: # can be used to pull the image from a specific docker registry
        tag: # can be used to pull a specific version of the image.
        pullPolicy: # "Always, IfNotPresent" default : not set
      resources:
        limits:
          memory: # The maximum memory to allocate to each pod
        requests:
          memory: # The minimum memory required to start a pod
          cpu: # The minimum amount of CPU required to start a pod

    #baiKafka: If you want to monitor ADW with BAI, uncomment this block and provide the necessary parameters
      # specify the ingress topic where ADW events should be sent
      #topic: "{{ meta.name }}-ibm-bai-ingress"
      #kerberosEnabled: # Set to true to enable Kerberos authentication to the Kafka server. Default is false
    #baiElasticsearch:
      # specify the URL of elasticSearch
      #url: ""
      # specify the URL of kibana
      #kibanaUrl: ""
