apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-oidc-client-registration
  namespace: "csNamespace"
  labels:
    component: cpfs3
spec:
  podSelector:
    matchLabels:
      app: "oidc-client-registration"
  policyTypes:
  - Egress
  egress:
  - {}