apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-platform-identity-provider
  namespace: "csNamespace"
  labels:
    component: cpfs3
spec:
  podSelector:
    matchLabels:
      k8s-app: "platform-identity-provider"
  policyTypes:
  - Egress
  egress:
  - {}