apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    component: cpfs3
  name: egress-common-web-ui
  namespace: "csNamespace"
spec:
  podSelector:
    matchLabels:
      k8s-app: common-web-ui
  policyTypes:
  - Egress
  egress:
  - {}
