apiVersion: operator.ibm.com/v1
kind: IBMServiceMeterDefinition
metadata:
  name: cp4ba-ban-metrics
  namespace: REPLACE_NAMESPACE
spec:
  mappingId: bandeployment000000000001
  processing: LAST
  repeat: true
  breakdownDefs:
    - breakdownBy:
        name: INSTANCE_COUNT
      groupBy:
        - version
        - environment
        - architecture
        - platform
      source: metricQuantity
      processing: LAST
  data:
    productId: 0f002233b583454d8a0bd72c665a01a3
    productName: Business Automation Navigator
    metricName: INSTANCE_COUNT
    metricDescription: count of BA Navigator instances
    metricType: ADOPTION
