apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-ibm-cert-manager-cainjector
  namespace: "certNamespace"
  labels:
    component: cpfs3
spec:
  egress:
    - ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6443
      to:
        - podSelector:
            matchLabels:
              apiserver: 'true'
          namespaceSelector: {}
  podSelector:
    matchLabels:
      app: "ibm-cert-manager-cainjector"
  policyTypes:
  - Egress