###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2020. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: <NAMESPACE>-cp4a-operator
  labels:
    app.kubernetes.io/instance: ibm-dba
    app.kubernetes.io/managed-by: ibm-dba
    app.kubernetes.io/name: ibm-dba
    release: 20.0.3
roleRef:
  name: ibm-cp4a-operator
subjects:
- kind: ServiceAccount
  name: ibm-cp4a-operator
  namespace: <NAMESPACE>
