apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: cp4a-file-retain-silver-gid
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: ibm.io/ibmc-file
parameters:
  type: "Endurance"
  iopsPerGB: "4"
  sizeRange: "[20-12000]Gi"
  billingType: "hourly"
  classVersion: "2"
  gidAllocate: "true"
reclaimPolicy: Retain
volumeBindingMode: Immediate