###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2020. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: icp4aclusters.icp4a.ibm.com
  labels:
    app.kubernetes.io/instance: ibm-dba
    app.kubernetes.io/managed-by: ibm-dba
    app.kubernetes.io/name: ibm-dba
    release: 20.0.2
spec:
  group: icp4a.ibm.com
  names:
    kind: ICP4ACluster
    listKind: ICP4AClusterList
    plural: icp4aclusters
    singular: icp4acluster
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
   # in kube 1.14 schemas can be version specific
    openAPIV3Schema:
      properties:
        spec:
          properties:
            appVersion:
              type: string
            spec:
              properties:
                version:
                  type: string
              type: object
            status:
              description: CloudPakAutomationStatus defines the observed state of Automation
              properties:
                cpAutoStatus:
                  description: It will be as "OK when all objects are created successfully
                  type: string
              required:
              - cpAutoStatus
              type: object
            license:
              type: string
              pattern: '^accept$'
            readinessProbe:
              properties:
                initialDelaySeconds:
                  type: integer
                  minimum: 5
                  maximum: 20
            queueManager:
              properties:
                dev:
                  properties:
                    adminPassword:
                      type: string
                      pattern: '^[a-zA-Z0-9]{8,}$'
