persistence:
  useDynamicProvisioning: true

imageCredentials:
  registry: <DOCKER_REGISTRY_URL>
  username: <DOCKER_REGISTRY_USERNAME>
  password: <DOCKER_REGISTRY_PASSWORD>

kafka:
  bootstrapServers: "<KAFKA_BROKERS_LIST>"
  securityProtocol: "SASL_SSL"
  username: "<KAFKA_USERNAME>"
  password: "<KAFKA_PASSWORD>"
  serverCertificate: "<BASE64_KAFKA_CA_CERT>"

settings:
  ingressTopic: "bai-release-ingress"
  egressTopic: "bai-release-egress"
  serviceTopic: "bai-release-service"

setup:
  image:
    repository: <DOCKER_REGISTRY_PATH>/bai-setup

admin:
  image:
    repository: <DOCKER_REGISTRY_PATH>/bai-admin
  externalPort: <BAI_ADMIN_EXTERNAL_PORT>

flinkPv:
  existingClaimName: "<BAI_FLINK_PVC_NAME>"

flink:
  image:
    repository: <DOCKER_REGISTRY_PATH>/bai-flink
  storageBucketUrl: "<HDFS_BUCKET_URL>"

  zookeeper:
    image:
      repository: <DOCKER_REGISTRY_PATH>/bai-flink/zookeeper

ingestion:
  image:
    repository: <DOCKER_REGISTRY_PATH>/bai-ingestion

bpmn:
  install: true
  image:
    repository: <DOCKER_REGISTRY_PATH>/bai-bpmn

bawadv:
  install: false

icm:
  install: false

odm:
  install: false

content:
  install: false

initImage:
  image:
    repository: <DOCKER_REGISTRY_PATH>/bai-init

ibm-dba-ek:
  image:
    credentials:
      registry: <DOCKER_REGISTRY_URL>
      username: <DOCKER_REGISTRY_USERNAME>
      password: <DOCKER_REGISTRY_PASSWORD>
  elasticsearch:
    init:
      image:
        repository: <DOCKER_REGISTRY_PATH>/bai-init
    image:
      repository: <DOCKER_REGISTRY_PATH>/bai-elasticsearch

    data:
      snapshotStorage:
        enabled: <BAI_ES_SNAPSHOT_STORAGE_ENABLED>
        existingClaimName: "<BAI_ES_SNAPSHOT_STORAGE_PVC>"
    client:
      externalPort: 31200

  kibana:
    image:
      repository: <DOCKER_REGISTRY_PATH>/bai-kibana
    externalPort: 31501