#!/bin/bash
###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2021. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
# CUR_DIR set to full path to scripts folder
CUR_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PARENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
TEMP_FOLDER=${CUR_DIR}/.tmp
OLM_SUBSCRIPTION=${PARENT_DIR}/descriptors/op-olm/subscription.yaml
OLM_SUBSCRIPTION_TMP=${TEMP_FOLDER}/.subscription.yaml

function select_uninstall_type(){
    local returnValue
    kubectl get subscription -n $NAMESPACE| grep ibm-cp4a-operator-catalog-subscription >/dev/null 2>&1
    returnValue=$?
    if [ "$returnValue" == 0 ] ; then
        uninstall_olm_cp4a
    elif [ "$returnValue" == 1 ] ; then
        uninstall_cp4a
    fi
}

function uninstall_cp4a(){
    printf "\n"
    printf "\x1B[1mUninstall CP4A Operator...\n\x1B[0m"
    kubectl delete -f ${CUR_DIR}/../descriptors/operator.yaml -n $NAMESPACE >/dev/null 2>&1
    kubectl delete -f ${CUR_DIR}/../descriptors/role_binding.yaml -n $NAMESPACE >/dev/null 2>&1
    kubectl delete -f ${CUR_DIR}/../descriptors/role.yaml -n $NAMESPACE >/dev/null 2>&1
    kubectl delete -f ${CUR_DIR}/../descriptors/service_account.yaml -n $NAMESPACE >/dev/null 2>&1
    echo "All descriptors have been successfully deleted."
}

function uninstall_olm_cp4a(){
    local csvName
    printf "\n"
    printf "\x1B[1mUninstall CP4A Operator Subscription...\n\x1B[0m"
    ${COPY_CMD} -rf "${OLM_SUBSCRIPTION}" "${OLM_SUBSCRIPTION_TMP}"
    ${SED_COMMAND} '/namespace: /d' ${OLM_SUBSCRIPTION_TMP}
    csvName=$(kubectl get subscription "ibm-cp4a-operator-catalog-subscription" -n $NAMESPACE -o go-template --template '{{.status.installedCSV}}')
    # - remove the subscription
    kubectl delete -f ${OLM_SUBSCRIPTION_TMP} -n $NAMESPACE >/dev/null 2>&1
    # - remove the CSV which was generated by the subscription but does not get garbage collected
    kubectl delete clusterserviceversion "${csvName}" >/dev/null 2>&1
    echo "The CP4A Operator Subscription has been successfully deleted."
}

function show_help {
    echo -e "\nPrerequisite:"
    echo -e "1. Login your cluster;"
    echo -e "2. CR was applied in your project."
    echo -e "Usage for other platform: deleteOperator.sh -n namespace\n"
    echo "Options:"
    echo "  -h  Display help"
    echo "  -n  The namespace to delete Operator"
}

if [[ $1 == "" ]]
then
    show_help
    exit -1
else
    while getopts "h?n:" opt; do
        case "$opt" in
        h|\?)
            show_help
            exit 0
            ;;
        n) NAMESPACE=$OPTARG
            ;;    
        :)  echo "Invalid option: -$OPTARG requires an argument"
            show_help
            exit -1
            ;;
        esac
    done
fi

mkdir -p $TEMP_FOLDER >/dev/null 2>&1
source ${CUR_DIR}/helper/common.sh
select_uninstall_type
rm -rf ${TEMP_FOLDER} >/dev/null 2>&1

