###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2026 All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
{{- if .Values.auth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.secretName }}
  labels:
    {{- include "cp4ba-api.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.auth.username | b64enc | quote }}
  password: {{ .Values.auth.password | b64enc | quote }}
{{- end }}