###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2022. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: ibm-dba-content
    app.kubernetes.io/managed-by: ibm-dba-content
    app.kubernetes.io/name: ibm-dba-content
    release: 24.0.0
  name: ibm-content-operator
  namespace: 
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      name: ibm-content-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: ibm-dba-content
        app.kubernetes.io/managed-by: ibm-dba-content
        app.kubernetes.io/name: ibm-dba-content
        name: ibm-content-operator
        release: 24.0.0
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - s390x
                - ppc64le
            weight: 3
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - s390x
                - ppc64le
      initContainers:
        - name: folder-prepare-container
          image: icr.io/cpopen/icp4a-content-operator@sha256:795f33fe5730c2b0124510bcf2501550ca7bf49a7950443876798a8e67740979
          imagePullPolicy: IfNotPresent
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: license-folder-pvc
              mountPath: /license-folder
            - name: ansible-folder-pvc
              mountPath: /ansible-folder
            - name: tmp-folder-pvc
              mountPath: /tmp-folder        
            - name: log-folder-pvc
              mountPath: /log-folder
            - name: ibm-folder-pvc
              mountPath: /ibm-folder
          command:
            - "/bin/sh"
            - "-ecx"
            - >
              rm -rf /license-folder/* && rm -rf /tmp-folder/* && rm -rf /ansible-folder/* && rm -rf /log-folder/* && rm -rf /ibm-folder/* &&
              cp -rp /licenses/* /license-folder && 
              mkdir -p /ansible-folder/.ansible &&
              cp -rp /opt/ansible/* /ansible-folder &&
              cp -rp /opt/ansible/.ansible/* /ansible-folder/.ansible &&
              cp -rp /opt/ibm/* /ibm-folder  
      containers:
      - args:
        - '--zap-encoder=console'
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: ibm-content-operator
        - name: MAX_CONCURRENT_RECONCILES_CONTENT_ICP4A_IBM_COM
          value: "10"
        - name: MAX_CONCURRENT_RECONCILES_CONTENTREQUEST_ICP4A_IBM_COM
          value: "1"
        - name: ANSIBLE_GATHERING
          value: smart
        - name: dba_license
          value: accept
        image: icr.io/cpopen/icp4a-content-operator@sha256:795f33fe5730c2b0124510bcf2501550ca7bf49a7950443876798a8e67740979
        imagePullPolicy: IfNotPresent
        name: operator
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
          - name: license-folder-pvc
            mountPath: /licenses
          - name: ansible-folder-pvc
            mountPath: /opt/ansible
          - name: tmp-folder-pvc
            mountPath: /tmp        
          - name: log-folder-pvc
            mountPath: /logs
          - name: ibm-folder-pvc
            mountPath: /opt/ibm
      securityContext:
        runAsNonRoot: true
      serviceAccountName: ibm-cp4a-content-operator
      imagePullSecrets:
      - name: "ibm-entitlement-key"
      volumes:
        - name: license-folder-pvc
          emptyDir: {}
        - name: tmp-folder-pvc
          emptyDir: {}
        - name: ansible-folder-pvc
          emptyDir: {}
        - name: log-folder-pvc
          emptyDir: {}
        - name: ibm-folder-pvc
          emptyDir: {}
