apiVersion: v1
kind: Service
metadata:
  name: ecm-crs-svc
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9080
      targetPort: 9080
    - name: https
      protocol: TCP
      port: 9443
      targetPort: 9443
  selector:
    app: crsserver-cluster1
  type: NodePort
  sessionAffinity: ClientIP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ecm-crs-np
  namespace: $KUBE_NAME_SPACE
spec:
   podSelector: {}
   policyTypes:
    - Ingress
    - Egress
   ingress:
   - {}
   egress:
   - ports:
     - port: 53
       protocol: UDP
     - port: 53
       protocol: TCP
   - to:
     - namespaceSelector: {}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ecm-crs
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: crsserver-cluster1
    spec:
      imagePullSecrets:
        - name: admin.registrykey
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - crsserver-cluster1
              topologyKey: "kubernetes.io/hostname"
      containers:
      - image: <Repository for Docker Container Image>/default/crs:553
        imagePullPolicy: Always
        securityContext:
          # If deployment on OpenShift and image supports arbitrary uid,
          # remove runAsUser and pods will run with arbitrarily assigned user ID.
          runAsUser: 50001
          allowPrivilegeEscalation: false
        name: ecm-crs
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 1536Mi
            cpu: 1
        ports:
        - containerPort: 9080
          name: http
        - containerPort: 9443
          name: https
        env:
          - name: LICENSE
            value: "accept"
          - name: PRODUCT
            value: "DBAMC"
          - name: TZ
            value: "Etc/UTC"
          - name: JVM_INITIAL_HEAP_PERCENTAGE
            value: "40"
          - name: JVM_MAX_HEAP_PERCENTAGE
            value: "66"
          - name: CPE_URI
            value: "http://cpeurl:30540/wsi/FNCEWS40MTOM"
          - name: CPESTATICPORT
            value: "false"
          - name: CONTAINERTYPE
            value: "1"
          - name: ENABLE_GRAPHIQL
            value: "false"  
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        volumeMounts:
          - name: crscfgstore-pvc
            mountPath: "/opt/ibm/wlp/usr/servers/defaultServer/configDropins/overrides"
            subPath: configDropins/overrides
          - name: crslogstore-pvc
            mountPath: "/opt/ibm/wlp/usr/servers/defaultServer/logs"
            subPath: logs

      volumes:
        - name: crscfgstore-pvc
          persistentVolumeClaim:
            claimName: "crs-cfgstore"
        - name: crslogstore-pvc
          persistentVolumeClaim:
            claimName: "crs-logstore"
