apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zen5-backup-rolebinding
  labels:
    foundationservices.cloudpak.ibm.com: zen5-data
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: zen5-backup-role
subjects:
- kind: ServiceAccount
  name: zen5-backup-sa