kind: Deployment
apiVersion: apps/v1
metadata:
  name: zen5-backup
  labels:
    foundationservices.cloudpak.ibm.com: zen5-data
spec:
  selector:
    matchLabels:
      foundationservices.cloudpak.ibm.com: zen5-data
  template:
    metadata:
      name: zen5-backup
      labels:
        foundationservices.cloudpak.ibm.com: zen5-data
    spec:
        containers:
        - command:
          - sh
          - -c
          - sleep infinity
          image: icr.io/cpopen/cpfs/cpfs-utils:4.3.0 #4.1.0 if using CS 4.1, 4.2.0 if using CS 4.2
          imagePullPolicy: IfNotPresent
          name: zen5-backup-job
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 512Mi
              memory: 512Mi
            requests:
              cpu: 200m
              ephemeral-storage: 128Mi
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /zen5/zen-backup
            name: zen5-backup-mount
          - name: scripts
            mountPath: "/zen5"
          - name: ext
            mountPath: /zen5/extensions
        dnsPolicy: ClusterFirst
        schedulerName: default-scheduler
        securityContext:
          runAsNonRoot: true
        serviceAccount: zen5-backup-sa
        serviceAccountName: zen5-backup-sa
        terminationGracePeriodSeconds: 30
        volumes:
        - name: zen5-backup-mount
          persistentVolumeClaim:
            claimName: zen5-backup-pvc
        - name: scripts
          configMap:
            name: zen5-br-configmap
            defaultMode: 0777
        - emptyDir: {}
          name: ext