apiVersion: velero.io/v1
kind: Restore
metadata:
  name: restore-pull-secret
  namespace: velero
spec:
  backupName: __BACKUP_NAME__
  excludedResources:
  - nodes
  - events
  - events.events.k8s.io
  - backups.velero.io
  - restores.velero.io
  - resticrepositories.velero.io
  hooks: {}
  includedNamespaces:
  - openshift-config
  labelSelector:
    matchLabels:
      foundationservices.cloudpak.ibm.com: pull-secret
