apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    component: cpfs3
  name: access-to-edb-postgres-webhooks
  namespace: "opNamespace"
spec:
  ingress:
  - {}
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cloud-native-postgresql
  policyTypes:
  - Ingress
